### ISSUE TITLE
thermal losses in pipes & demand pattern for valve setting 

### ISSUE THREAD

**Issue by flamuf** [USEPA/EPANET2.2#55]
Hi everyone

I am not sure if some already faced with this issues.
For simulations of district heating networks with Epanet it would be very useful if the thermal losses of the pipes (change of fluid temperature in a pipe due to surrounding --> constant temperature or temperature pattern) can be considered and if there would be a posibility to set time patterns for the valve setting.
Did someone face with that or has something similar been done yet (the physical knowledge I have but my programming skills are limited)?

Thanks much and regards!

**Comment by ucchejbb** [comment]
Thank you for your interest in EPANET, however, at this time temperature is not directly considered in EPANET models.
